// <auto-generated />
namespace MDIGestionScolaire.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Premier_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Premier_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202501150054580_Premier_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
